### ISSUE TITLE
void cutlass::arch::ldsm(cutlass::Array<unsigned int, MatrixCount, true> &, const void *) [with Layout = cutlass::layout::RowMajor; int MatrixCount = 4] not implemented

### ISSUE THREAD

**Issue by windyarts** [Oneflow-Inc/diffusers#381]
While trying the [LCM example script](https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_lcm.py), it raise error log for `void cutlass::arch::ldsm(cutlass::Array<unsigned int, MatrixCount, true> &, const void *) [with Layout = cutlass::layout::RowMajor; int MatrixCount = 4] not implemented` if oneflow is enabled.

The full log was like 
```
void cutlass::arch::ldsm(cutlass::Array<unsigned int, MatrixCount, true> &, const void *) [with Layout = cutlass::layout::RowMajor; int MatrixCount = 4] not implemented
F20231129 14:25:56.524652 1009523 cutlass_conv_tuner.cpp:283] Check failed: cudaEventSynchronize(end) : unspecified launch failure (719) 
*** Check failure stack trace: ***
    @     0x7ff77546f67a  google::LogMessage::Fail()
    @     0x7ff7754723b1  google::LogMessage::SendToLog()
    @     0x7ff77546f178  google::LogMessage::Flush()
    @     0x7ff775472a39  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff76e8ce7b7  oneflow::CutlassConvTuner::Impl::FindConv2dOperation()
    @     0x7ff76d67fe3e  _ZZNK7oneflow12_GLOBAL__N_127CutlassConvTuningWarmupPass5ApplyEPNS_3JobEPNS_10JobPassCtxEENKUlPKNS_6OpNodeEE_clES8_
    @     0x7ff76d680f90  oneflow::(anonymous namespace)::CutlassConvTuningWarmupPass::Apply()
    @     0x7ff76d52c2be  _ZZN7oneflow23LazyJobBuildAndInferCtx8CompleteEvENKUlRKSsiE2_clES2_i
    @     0x7ff76d5314e9  oneflow::LazyJobBuildAndInferCtx::Complete()
    @     0x7ff87d9fdcde  oneflow::CurJobBuildAndInferCtx_Complete()
    @     0x7ff87d9f6d70  (unknown)
    @     0x7ff87dc58875  (unknown)
    @     0x5641dd58710e  (unknown)
    @     0x5641dd57da7b  _PyObject_MakeTpCall
    @     0x5641dd576629  _PyEval_EvalFrameDefault
    @     0x5641dd5957f1  (unknown)
    @     0x5641dd596492  PyObject_Call
    @     0x5641dd5725d7  _PyEval_EvalFrameDefault
    @     0x5641dd5957f1  (unknown)
    @     0x5641dd596492  PyObject_Call
    @     0x5641dd5725d7  _PyEval_EvalFrameDefault
    @     0x5641dd5957f1  (unknown)
    @     0x5641dd596492  PyObject_Call
    @     0x5641dd5725d7  _PyEval_EvalFrameDefault
    @     0x5641dd5957f1  (unknown)
    @     0x5641dd596492  PyObject_Call
    @     0x5641dd5725d7  _PyEval_EvalFrameDefault
    @     0x5641dd5879fc  _PyFunction_Vectorcall
    @     0x5641dd57ccbd  _PyObject_FastCallDictTstate
    @     0x5641dd59286c  _PyObject_Call_Prepend
    @     0x5641dd6ad700  (unknown)
    @     0x5641dd59642b  PyObject_Call
Stack trace (most recent call last):
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/_oneflow_internal.cpython-310-x86_64-linux-gnu.so", at 0x7ff87dc58874, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/_oneflow_internal.cpython-310-x86_64-linux-gnu.so", at 0x7ff87d9f6d6f, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/_oneflow_internal.cpython-310-x86_64-linux-gnu.so", at 0x7ff87d9fdcdd, in CurJobBuildAndInferCtx_Complete()
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff76d5314e8, in LazyJobBuildAndInferCtx::Complete()
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff76d52c2bd, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff76d680f8f, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff76d67fe3d, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff76e8ce7b6, in CutlassConvTuner::Impl::FindConv2dOperation(ep::CudaStream*, cutlass::library::ConvFunctionalKey, cutlass::library::Conv2dConfiguration const&, cutlass::library::ConvArguments const&, void*, unsigned long)
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff775472a38, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff77546f177, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff7754723b0, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff77546f679, in 
   Object "/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-7ae8cf33.so", at 0x7ff766a7b9d4, in 
``` 
with the full one as in attachment 
[oneflow.log](https://github.com/Oneflow-Inc/diffusers/files/13497860/oneflow.log)

It was able to run with oneflow disabled(by adding --disable flag). Here's my environment settings:
```
$ pip list

Package                  Version                 Editable project location
------------------------ ----------------------- ------------------------------------------------------
accelerate               0.24.1
certifi                  2023.11.17
chardet                  5.2.0
charset-normalizer       3.3.2
diffusers                0.23.1
filelock                 3.13.1
fsspec                   2023.10.0
huggingface-hub          0.19.4
idna                     3.6
importlib-metadata       6.8.0
Jinja2                   3.1.2
markdown-it-py           3.0.0
MarkupSafe               2.1.3
mdurl                    0.1.2
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.26.2
nvidia-cublas-cu11       11.11.3.6
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu11   11.8.89
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu11        8.9.6.50
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
onediff                  0.11.0.dev0             /home/ecs-user/sd-deployments/onediff-test/onediff/src
oneflow                  0.9.1+cu121.git.c9b6f23
onefx                    0.0.3
opencv-python            4.8.1.78
packaging                23.2
Pillow                   10.1.0
pip                      22.0.2
protobuf                 3.20.3
psutil                   5.9.6
Pygments                 2.17.2
PyYAML                   6.0.1
regex                    2023.10.3
requests                 2.31.0
rich                     13.7.0
safetensors              0.4.1
setuptools               59.6.0
sympy                    1.12
tokenizers               0.13.3
torch                    2.1.1
tqdm                     4.66.1
transformers             4.27.1
triton                   2.1.0
typing_extensions        4.8.0
urllib3                  2.1.0
zipp                     3.17.0
```

```
$ nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:07.0 Off |                    0 |
| N/A   36C    P0    24W /  70W |   2391MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by strint** [comment]
Got this. We will look into it.

**Comment by strint** [comment]
Please run `python -m oneflow --doctor` and paste oneflow version info here.

**Comment by windyarts** [comment]
Here's the output @strint 
```
$ python -m oneflow --doctor

path: ['/home/ecs-user/sd-deployments/onediff-test/lib/python3.10/site-packages/oneflow']
version: 0.9.1+cu121.git.c9b6f23
git_commit: c9b6f23
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by strint** [comment]
It seems that you have CUDA Version: 12.0

Did you  install the right cuda versioin?

This is for cuda 12:
```
python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu121
```

**Comment by windyarts** [comment]
Yes it is for cuda 12 @strint 
```
$ pip list | grep oneflow
oneflow                  0.9.1+cu121.git.c9b6f23
```

**Comment by strint** [comment]
It turns out that Tesla T4 is not supported for the moment.

You need to run on other devices. 

If there is a huge demand on Tesla T4, please let us know by https://github.com/Oneflow-Inc/diffusers#business-inquiry-on-onediff-enterprise-version

**Comment by windyarts** [comment]
Thanks, I'll try other devices.
